### ISSUE TITLE
Blank cells on export to excel

### ISSUE THREAD

**Issue by syarifmaulanamm** [didanurwanda/DataTables-Export-Document#2]
Hi! I can't see my data in exported excel file.
The result showing 3 rows like my data in datatables but only blank cells like image below.

![Image of screenshot ](https://image.prntscr.com/image/KFoK6b-qS9Sg7qXqN68taQ.png)

And this is my code:

```
var dt = $('.datatables').DataTable();

$('body').on('click', '#btnExportExcel', function(e) {
    $.fn.DataTable.Export.excel(dt, {
        filename: 'Data Kelas',
        title: 'Kelas',
        message: 'Data Kelas',
        header: [
            'No.',
            'Nama Kelas'
        ],
        field: [
            0,
            1
        ]
    });
});
```

**Comment by syarifmaulanamm** [comment]
I've tried other methods like word, print, etc but I still have this kind of problem

**Comment by didanurwanda** [comment]
There is a typing error in the documentation. Change "field" to "fields".
